#!/bin/sh

# Dependencies: acpi, lm-sensors

bat=$(acpi -b | grep -E '[1-9][0-9]?[0]?%' | cut -c 9-9)

percent=$(acpi -b | grep -E -o '[1-9][0-9]?[0]?%')
state=$(LANG= acpi -b | grep "Battery ${bat}:" | grep -E -o "Unknown|Charging|Discharging|Full|Not charging")
addInfo=""

wattage() {
	UPOWER_OUTPUT="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)"
	addInfo="BAT $(echo "${UPOWER_OUTPUT}" | grep energy-rate | grep -Eo '[0-9]{1,3}\.[0-9]{1,4} m?W')"
	#sensors=$(sensors)
	#voltage="$(echo "$sensors" | grep BAT -A2 | grep -E -o "[0-9]?[0-9]?[0-9].[0-9][0-9]?\ m?V")"
	#if [ -z "${voltage##*"m"*}" ]
	#then
	#	voltage=$(echo "$voltage" | sed 's/\ mV//')
	#	voltage=$(echo "$voltage" | LANG=C awk '{print $1/1000}')
	#else
	#	voltage=$(echo "$voltage" | sed 's/\ V//');
	#fi

	#amps="$(echo "$sensors" | grep BAT -A2 | grep -E -o "[0-9]?[0-9]?[0-9].[0-9][0-9]?\ m?A")"
	#if [ -z "${amps##*"m"*}"]
	#then
	#	amps=$(echo "$amps" | sed 's/\ mA//')
	#	amps=$(echo "$amps" | LANG=C awk '{print $1/1000}')
	#else
	#	amps=$(echo "$amps" | sed 's/\ A//');
	#fi
	#addInfo=$(echo "$voltage $amps" | LANG=C awk '{printf "%5.2f W", $1*$2}')
}

voltage() {
	UPOWER_OUTPUT="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)"
	addInfo="$(echo "${UPOWER_OUTPUT}" | grep voltage | grep -Eo '[0-9]{1,3}\.[0-9]{1,4} m?V')"
	#addInfo="$(sensors | grep BAT -A2 | grep -E -o "[0-9]?[0-9]?[0-9].[0-9][0-9]?\ m?V")"
}

amps() {
	#UPOWER_OUTPUT="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)"
	#addInfo="$(echo "${UPOWER_OUTPUT}" | grep energy-rate | grep -Eo '[0-9]{1,3}\.[0-9]{1,4} m?W')"
	addInfo="$(sensors | grep BAT -A2 | grep -E -o "[0-9]?[0-9]?[0-9].[0-9][0-9]?\ m?A")"
}

time() {
	UPOWER_OUTPUT="$(upower -i /org/freedesktop/UPower/devices/battery_BAT0)"
	addInfo="$(echo "${UPOWER_OUTPUT}" | grep 'time to' | grep -Eo '[0-9].*$')"
	#addInfo=$(acpi -b | sed -n "/${bat}/p" | grep -E -o '([0-9]?[0-9]:)?[0-9]?[0-9]:[0-9][0-9]')
}

# Adjust these lines to fulfill all needs and all possibilities
case $BLOCK_BUTTON in
	3)	time ;;
	4)	voltage ;;
	2)  wattage ;;
	#5)  amps ;;
	*)	addInfo="" ;;
esac

case $state in
	Unknown) icon="🔌🔋" ;;
	"Not charging") icon="🔌🔋" ;;
	Charging) icon="🔌🗲🔋" ;;
	Discharging) icon="🔋" ;;
	Full) icon="🔌🔋" ;;
esac

if [ "$addInfo" != "" ]
then
	echo "${icon} ${addInfo}"
	echo "${icon}${addInfo}"
else
	echo "${icon} ${percent}"
	echo "${icon}${percent}"
fi

if [ ${percent%?} -le "8" ]
then
	exit 33;
elif [ ${percent%?} -le "15" ]
then
	echo "#FF8000"
elif [ ${percent%?} -le "20" ]
then
	echo "#FFFF00"
elif [ ${percent%?} -le "30" ]
then
	echo "#FFFFB0"
elif [ ${percent%?} -ge "90" ]
then
	echo "#B0D0FF"
else
	echo "#FFFFFF"
fi
exit 0
