#!/bin/sh

# Dependencies: date

hour=$(date +%H)

case $hour in
	00|12) clk="🕛" ;;
	01|13) clk="🕐" ;;
	02|14) clk="🕑" ;;
	03|15) clk="🕒" ;;
	04|16) clk="🕓" ;;
	05|17) clk="🕔" ;;
	06|18) clk="🕕" ;;
	07|19) clk="🕖" ;;
	08|20) clk="🕗" ;;
	09|21) clk="🕘" ;;
	10|22) clk="🕙" ;;
	11|23) clk="🕚" ;;
esac

echo $clk
exit 0
	 
