#!/bin/bash

. /home/josef/.config/sway/notification_status.sh

current_brightness=$(brightnessctl get)
max_brightness=$(brightnessctl max)

case "$1" in
	"--set")
		if [ "$#" != "2" ]
		then
			echo "error: expected one argument after --set!"
			exit 1
		fi
		if [ "$2" = "off" ]
		then
			brightnessctl set 1 # may, on some systems, actually be 0
			show_notification_status brightness "off"
			exit 0
		fi
		current_brightness="$((${2%\%*}*$max_brightness/100))"
		brightnessctl set "$current_brightness"
		show_notification_status brightness "Screen brightness: $(($(brightnessctl g)*100/$max_brightness))%"
		;;
	"--inc")
		if [ "$#" != "2" ]
		then
			echo "error: expected one argument after --inc!"
			exit 2
		fi
		current_brightness="$(($current_brightness + (${2%\%*} * $max_brightness / 100)))"
		current_brightness="$(($current_brightness > $max_brightness ? $max_brightness : $current_brightness))"
		brightnessctl set "$current_brightness"
		show_notification_status brightness "Screen brightness: $(($(brightnessctl g)*100/$max_brightness))%"
		;;
	"--dec")
		if [ "$#" != "2" ]
		then
			echo "error: expected one argument after --dec!"
			exit 3
		fi
		current_brightness="$(($current_brightness - (${2%\%*} * $max_brightness / 100)))"
		current_brightness="$(($current_brightness < 1 ? 1 : $current_brightness))"
		brightnessctl set "$current_brightness"
		show_notification_status brightness "Screen brightness: $(($(brightnessctl g)*100/$max_brightness))%"
		;;
	"--mul")
		if [ "$#" != "2" ]
		then
			echo "error: expected one argument after --mul!"
			exit 4;
		fi
		current_brightness="$(($current_brightness * (${2%\%*}) / 100))"
		brightnessctl set "$current_brightness"
		show_notification_status brightness "Screen brightness: $(($(brightnessctl g)*100/$max_brightness))%"
		;;\
	"--get")
		if [ "$#" != "2" ] || [ "$2" = "%" ] || [ "$2" = "percent" ];
		then
			echo "$(($current_brightness*100/$max_brightness))%"
		elif [ "$2" = "absolute" ]
		then
			echo "$current_brightness"
		elif [ "$2" = "abs/max" ]
		then
			echo "$current_brightness / $max_brightness"
		else
			echo "only 'percent', '%', 'absolute' and 'abs/max' are permitted!"
			exit 5;
		fi
		;;
	*)
		echo $'Usage:
	--set:       Sets the screen brightness at an absolute value in percent
	--inc:       Increments screen brightness by a given value
	--dec:       Decrements screen brightness by a given value
	--get [arg]: Get current brightness. Possible arguments are: "percent", "%", "absolute" and "abs/max"
	--mul:		Multiplies the current brightness by a given value'
		exit 0
		;;
esac
