#!/bin/sh

brightness_sh="/home/josef/.config/sway/brightness"
current=$($brightness_sh --get | tr -d '%' | awk '{printf "%.1f%%", $1}')

$brightness_sh --set $(echo "currently: $current\noff\n0%\n2%\n5%\n10%\n20%\n40%\n60%\n80%\n100%" | wofi -dmenu -p "backlight" -L 12 -w1 --width 16 -O alphabetical | tr -d 'currently: ' | tr ',' '.')
