#!/bin/bash

. /home/josef/.config/sway/notification_status.sh

CARDS="$(pactl list short cards)"
CARD="$(echo "$CARDS" | cut -f2 | head -n1)"

DEFAULT_SINK="$(pactl get-default-sink)"
if [[ "$DEFAULT_SINK" =~ "Thunderbolt" ]]; then
	pactl set-card-profile "$CARD" 'HiFi (HDMI1, HDMI2, HDMI3, Mic1, Mic2, Speaker)'
	pactl set-default-sink "alsa_output.pci-0000_00_1f.3-platform-skl_hda_dsp_generic.HiFi__Speaker__sink"
	show_notification_status paprofile "Using laptop speaker"
	exit
fi
if [[ "$CARDS" =~ "Thunderbolt" ]]; then
	pactl set-card-profile "$CARD" 'HiFi (HDMI1, HDMI2, HDMI3, Headphones, Mic1, Mic2)'
	pactl set-default-sink "alsa_output.usb-Lenovo_ThinkPad_Thunderbolt_3_Dock_USB_Audio_000000000000-00.analog-stereo"
	show_notification_status paprofile "Using dock output"
	exit
fi

NEW_PROFILE="$(pactl list cards | grep 'Active Profile' | head -n1 | grep -q Speaker && echo 'Headphones' || echo 'Speakers')"
CARD="$(echo "$CARDS" | cut -f2 | head -n1)"

if [ "$NEW_PROFILE" = "Headphones" ]; then
	pactl set-card-profile "$CARD" 'HiFi (HDMI1, HDMI2, HDMI3, Headphones, Mic1, Mic2)'
else
	pactl set-card-profile "$CARD" 'HiFi (HDMI1, HDMI2, HDMI3, Mic1, Mic2, Speaker)'
fi

show_notification_status paprofile "Using $NEW_PROFILE"
