#!/bin/bash

. /home/josef/.config/sway/notification_status.sh

MONITOR="Fujitsu Siemens Computers GmbH P27-8 TS Pro YVAQ607198"

swaymsg -t get_outputs \
	| jq '.[] | select((.make + " " + .model + " " + .serial)  == "'"$MONITOR"'") | [.transform, .rect.x, .rect.y] | @tsv' -r \
	| while IFS=$'\t' read TRANSFORM XPOS YPOS; do
	echo $TRANSFORM
	echo $XPOS
	echo $YPOS

	if [ "$TRANSFORM" = 90 ] && [ "$XPOS" = 11536 ] && [ "$YPOS" = 8025 ]; then
		TRANSFORM=0
		XPOS=11536
		YPOS=8560
	else
		TRANSFORM=90
		XPOS=11536
		YPOS=8025
	fi

	echo $TRANSFORM
	echo $XPOS
	echo $YPOS

	swaymsg output "'$MONITOR'" transform $TRANSFORM pos $XPOS $YPOS
	show_notification_status monitor_rotate "Screen rotation: $TRANSFORM°"
done

