" Vim syntax file
" Language: Intel SGX Enclave Definition Language (EDL)
" Latest Revision: 2026-08-07
" Fully generated by ChatGPT

if exists("b:current_syntax")
    finish
endif

" Reuse the C syntax as a base.
runtime! syntax/c.vim
unlet! b:current_syntax

" ---------------------------------------------------------------------
" Keywords
" ---------------------------------------------------------------------

syntax keyword edlKeyword enclave trusted untrusted public
syntax keyword edlKeyword import from include

" ---------------------------------------------------------------------
" Parameter attributes
" ---------------------------------------------------------------------

syntax keyword edlAttribute in out user_check string wstring
syntax keyword edlAttribute size count isptr readonly
syntax keyword edlAttribute unique optional
syntax keyword edlAttribute direction

" Attributes inside [...]
syntax region edlAttributeBlock start="\[" end="\]" contains=edlAttribute,cNumber,cOperator,cType

" ---------------------------------------------------------------------
" Import statements
" ---------------------------------------------------------------------

syntax region edlImport
      \ start="\<from\>"
      \ end=";"
      \ contains=edlKeyword,cString,cIncluded

syntax match edlImportStar /\*/

" ---------------------------------------------------------------------
" Top-level blocks
" ---------------------------------------------------------------------

syntax region edlTrusted
      \ start="\<trusted\>\s*{"
      \ end="}"
      \ transparent
      \ fold

syntax region edlUntrusted
      \ start="\<untrusted\>\s*{"
      \ end="}"
      \ transparent
      \ fold

syntax region edlEnclave
      \ start="\<enclave\>\s*{"
      \ end="};\?"
      \ transparent
      \ fold

" ---------------------------------------------------------------------
" Function modifiers
" ---------------------------------------------------------------------

syntax match edlPublic /\<public\>\ze\s\+\k\+\s*(/

" ---------------------------------------------------------------------
" Highlighting
" ---------------------------------------------------------------------

highlight default link edlKeyword      Keyword
highlight default link edlAttribute    StorageClass
highlight default link edlAttributeBlock Special
highlight default link edlImport       Include
highlight default link edlImportStar   Special
highlight default link edlPublic       StorageClass

let b:current_syntax = "edl"
